[versions]
#production dependencies
lombok = "1.18.42"
spring-boot = "3.5.6"
spring-dep-mgmt = "1.1.7"
kafka-streams = "3.9.0"
annotation-api = "1.3.2"
awaitality = "4.2.2"

#test dependencies
mockito = "5.20.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }

[libraries]
#production dependencies
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

#kafka streams
kafka-streams = { group = "org.apache.kafka", name = "kafka-streams", version.ref = "kafka-streams" }

#other
annotation-api = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "annotation-api" }
awaitality = { group = "org.awaitility", name = "awaitility", version.ref = "awaitality" }

#test dependencies
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }

